title: Letter's from the wasteland
author: Aditya Kumar
email: aditya2507@gmail.com
description: (living under the pandemic).
url: "http://adityeah.github.io" 

# Build settings
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed

moving:
  about_you: Hard work always pays off
  avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png 
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github:  huangyz0918
    facebook: huangyz0918
    linkedin: yizheng-huang
