title: Letters from the wasteland
author: aditya kumar
email: aditya two five zero seven  [at] gmail [dot] com
description: Hard work always pays off.
url: "http://adityeah.github.io" 

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Blogging in a pandemic
  #avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png 
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    #github:  huangyz0918
    #facebook: huangyz0918
    #linkedin: yizheng-huang

